---
extends:
  - airbnb-base
  - plugin:flowtype/recommended
  - prettier
  - prettier/flowtype
rules:
  no-use-before-define: 0
  class-methods-use-this: 0
  no-constant-condition: 0
  no-duplicate-imports: 0
  no-else-return: 0
  no-plusplus: 0
  arrow-body-style: 0
  import/prefer-default-export: 0
  prefer-destructuring: 0
  prettier/prettier: 2
env:
  jest: true
parser: 'babel-eslint'
plugins:
  - flowtype
  - prettier
